name: Continuous Deployment to VPS [Linux]

on:
  push:
    branches:
      - "**"
    paths: 
      - "vps-infrastructure/**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "continuous-deployment-vps"
  cancel-in-progress: false        

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Get the microservice version from README.md
        id: version
        run: |
          echo "PRP_PRD=$(cat README.md | grep -o -P '(?<=<!-- etl-prd-start -->).*(?=<!-- etl-prd-end -->)')" >> $GITHUB_ENV

      - name: Build Image URL
        id: build_image_url
        run: |
          echo "IMAGE_URL=${{ vars.DOCKER_REGISTRY }}/jtsato/${{ vars.ARTIFACT_NAME }}:${{ env.PRP_PRD }}" >> $GITHUB_ENV

      - name: Set Environment Variables from GitHub Secrets
        env:
          IMAGE_URL: ${{ env.IMAGE_URL }}
          PRP_PRD: ${{ env.PRP_PRD }}
        run: |
          echo "TF_LOG=debug" >> $GITHUB_ENV
          echo "TF_VAR_IMAGE_URL=${{ env.IMAGE_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> $GITHUB_ENV
          echo "TF_VAR_AI_PROMPT=${{ vars.AI_PROMPT }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_SEARCH_PROPERTIES_URL=${{ vars.T1_SEARCH_PROPERTIES_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_IMGS_PATTERN_PREFIX_URL=${{ vars.T1_IMGS_PATTERN_PREFIX_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_LOAD_TIMEOUT_IN_SECONDS=${{ vars.T1_LOAD_TIMEOUT_IN_SECONDS }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_XPATH_TIMEOUT_IN_SECONDS=${{ vars.T1_XPATH_TIMEOUT_IN_SECONDS }}" >> $GITHUB_ENV
          echo "TF_VAR_CLOUDAMQP_URL=${{ secrets.CLOUDAMQP_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_USER=${{ secrets.MONGODB_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_PROPERTY_COLLECTION_NAME=${{ vars.PROPERTY_COLLECTION_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_USER=${{ secrets.SSH_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_HOST=${{ secrets.SSH_HOST }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_PORT=${{ secrets.SSH_PORT }}" >> $GITHUB_ENV
          echo "TF_VAR_GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}" >> $GITHUB_ENV

      - name: Terraform Version
        run: terraform -version

      - name: Terraform Init
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Terraform validate
        working-directory: vps-infrastructure
        run: |
          terraform validate

      - name: Verify Terraform Providers
        working-directory: vps-infrastructure
        run: |
          terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64

      - name: Create secrets.tfvars
        working-directory: vps-infrastructure
        run: |
          echo "image_url=\"$TF_VAR_IMAGE_URL\"" >> secrets.tfvars
          echo "log_level=\"$TF_VAR_LOG_LEVEL\"" >> secrets.tfvars
          echo "ai_prompt=\"$TF_VAR_AI_PROMPT\"" >> secrets.tfvars
          echo "t1_search_properties_url=\"$TF_VAR_T1_SEARCH_PROPERTIES_URL\"" >> secrets.tfvars
          echo "t1_imgs_pattern_prefix_url=\"$TF_VAR_T1_IMGS_PATTERN_PREFIX_URL\"" >> secrets.tfvars
          echo "t1_load_timeout_in_seconds=\"$TF_VAR_T1_LOAD_TIMEOUT_IN_SECONDS\"" >> secrets.tfvars
          echo "t1_xpath_timeout_in_seconds=\"$TF_VAR_T1_XPATH_TIMEOUT_IN_SECONDS\"" >> secrets.tfvars
          echo "cloudamqp_url=\"$TF_VAR_CLOUDAMQP_URL\"" >> secrets.tfvars
          echo "openai_api_key=\"$TF_VAR_OPENAI_API_KEY\"" >> secrets.tfvars
          echo "perplexity_api_key=\"$TF_VAR_PERPLEXITY_API_KEY\"" >> secrets.tfvars
          echo "mongodb_url=\"$TF_VAR_MONGODB_URL\"" >> secrets.tfvars
          echo "mongodb_database=\"$TF_VAR_MONGODB_DATABASE\"" >> secrets.tfvars
          echo "mongodb_user=\"$TF_VAR_MONGODB_USER\"" >> secrets.tfvars
          echo "mongodb_password=\"$TF_VAR_MONGODB_PASSWORD\"" >> secrets.tfvars
          echo "property_collection_name=\"$TF_VAR_PROPERTY_COLLECTION_NAME\"" >> secrets.tfvars
          echo "ssh_user=\"$TF_VAR_SSH_USER\"" >> secrets.tfvars
          echo "ssh_password=\"$TF_VAR_SSH_PASSWORD\"" >> secrets.tfvars
          echo "ssh_host=\"$TF_VAR_SSH_HOST\"" >> secrets.tfvars
          echo "ssh_port=\"$TF_VAR_SSH_PORT\"" >> secrets.tfvars
          echo "google_credentials=\"$TF_VAR_GOOGLE_CREDENTIALS\"" >> secrets.tfvars

      - name: Terraform Destroy
        working-directory: vps-infrastructure
        continue-on-error: true
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform destroy -auto-approve -var-file=secrets.tfvars

      - name: Terraform Refresh
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform refresh -var-file=secrets.tfvars

      - name: Terraform State List
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform state list

      - name: Terraform Plan
        working-directory: vps-infrastructure
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform plan -out=tfplan.out -var-file=secrets.tfvars

      - name: Terraform Apply
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve tfplan.out

  deploy-service:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}      

      - name: Get the microservice version from README.md
        id: version
      run: |
        echo "PRP_PRD=$(cat README.md | grep -o -P '(?<=<!-- etl-prd-start -->).*(?=<!-- etl-prd-end -->)')" >> $GITHUB_ENV

      - name: Build Image URL
        id: build_image_url
      run: |
        echo "IMAGE_URL=${{ vars.DOCKER_REGISTRY }}/jtsato/${{ vars.ARTIFACT_NAME }}:${{ env.PRP_PRD }}" >> $GITHUB_ENV

      - name: Set Environment Variables from GitHub Secrets
      env:
        IMAGE_URL: ${{ env.IMAGE_URL }}
        run: |
        echo "SERVICE_NAME=${{ vars.SERVICE_NAME }}" >> $GITHUB_ENV
        echo "IMAGE_URL=${{ env.IMAGE_URL }}" >> $GITHUB_ENV
        echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> $GITHUB_ENV
        echo "AI_PROMPT=${{ vars.AI_PROMPT }}" >> $GITHUB_ENV
        echo "T1_SEARCH_PROPERTIES_URL=${{ vars.T1_SEARCH_PROPERTIES_URL }}" >> $GITHUB_ENV
        echo "T1_IMGS_PATTERN_PREFIX_URL=${{ vars.T1_IMGS_PATTERN_PREFIX_URL }}" >> $GITHUB_ENV
        echo "T1_LOAD_TIMEOUT_IN_SECONDS=${{ vars.T1_LOAD_TIMEOUT_IN_SECONDS }}" >> $GITHUB_ENV
        echo "T1_XPATH_TIMEOUT_IN_SECONDS=${{ vars.T1_XPATH_TIMEOUT_IN_SECONDS }}" >> $GITHUB_ENV
        echo "BUCKET_NAME=${{ vars.BUCKET_NAME }}" >> $GITHUB_ENV
        echo "CLOUDAMQP_URL=${{ secrets.CLOUDAMQP_URL }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> $GITHUB_ENV
        echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV
        echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> $GITHUB_ENV
        echo "MONGODB_USER=${{ secrets.MONGODB_USER }}" >> $GITHUB_ENV
        echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
        echo "PROPERTY_COLLECTION_NAME=${{ vars.PROPERTY_COLLECTION_NAME }}" >> $GITHUB_ENV
        echo "GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}" >> $GITHUB_ENV        

      - name: Create Docker Compose File
        working-directory: vps-services
      id: create_docker_compose
      run: |
        python create_docker_compose.py

      - name: Copy Docker Compose File to Remote Server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /home/${{ secrets.SSH_USER }}/${{ vars.SERVICE_NAME }}"
          scp -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/${{ vars.SERVICE_NAME }}/docker-compose.yml

      - name: Start Docker Compose
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/${{ vars.SERVICE_NAME }} && docker-compose down"
          ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/${{ vars.SERVICE_NAME }} && docker-compose up -d"

      - name: Check Docker Compose Status
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/${{ vars.SERVICE_NAME }} && docker-compose ps"

      - name: Check Docker Compose Logs
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/${{ vars.SERVICE_NAME }} && docker-compose logs"

      - name: Environment Teardown
        if: always()
      run: |
        echo "Finished!"
