name: Continuous Deployment to GCP [Linux]

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "continuous-deployment"
  cancel-in-progress: false

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Get the microservice version from README.md
        id: version
        run: |
          echo "PRP_PRD=$(cat README.md | grep -o -P '(?<=<!-- etl-prd-start -->).*(?=<!-- etl-prd-end -->)')" >> $GITHUB_ENV

      - name: Build Image URL
        id: build_image_url
        run: |
          echo "IMAGE_URL=${{ vars.DOCKER_REGISTRY }}/jtsato/${{ vars.ARTIFACT_NAME }}:${{ env.PRP_PRD }}" >> $GITHUB_ENV

      - name: Set Environment Variables from GitHub Secrets
        env:
          IMAGE_URL: ${{ env.IMAGE_URL }}
          PRP_PRD: ${{ env.PRP_PRD }}
        run: |
          echo "ARTIFACT=${{ env.IMAGE_URL }}:${{ env.PRP_PRD }}"
          echo "TF_LOG=debug" >> $GITHUB_ENV
          echo "TF_VAR_PROJECT_ID=${{ vars.PROJECT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_CLOUD_REGION=${{ vars.CLOUD_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_ZONE=${{ vars.ZONE }}" >> $GITHUB_ENV
          echo "TF_VAR_SERVICE_NAME=${{ vars.SERVICE_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_IMAGE_URL=${{ env.IMAGE_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_TZ=${{ vars.TZ }}" >> $GITHUB_ENV
          echo "TF_VAR_LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> $GITHUB_ENV
          echo "TF_VAR_AI_PROMPT=${{ vars.AI_PROMPT }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_SEARCH_PROPERTIES_URL=${{ vars.T1_SEARCH_PROPERTIES_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_IMGS_PATTERN_PREFIX_URL=${{ vars.T1_IMGS_PATTERN_PREFIX_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_LOAD_TIMEOUT_IN_SECONDS=${{ vars.T1_LOAD_TIMEOUT_IN_SECONDS }}" >> $GITHUB_ENV
          echo "TF_VAR_T1_XPATH_TIMEOUT_IN_SECONDS=${{ vars.T1_XPATH_TIMEOUT_IN_SECONDS }}" >> $GITHUB_ENV
          echo "TF_VAR_SERVER_HOST=${{ secrets.SERVER_HOST }}" >> $GITHUB_ENV
          echo "TF_VAR_SERVER_PORT=${{ secrets.SERVER_PORT }}" >> $GITHUB_ENV
          echo "TF_VAR_CLOUDAMQP_URL=${{ secrets.CLOUDAMQP_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> $
          echo "TF_VAR_MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_USER=${{ secrets.MONGODB_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_PROPERTY_COLLECTION_NAME=${{ vars.PROPERTY_COLLECTION_NAME }}" >> $GITHUB_ENV

      - name: Terraform Version
        run: terraform -version

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Terraform validate
        run: |
          terraform validate

      - name: Verify Terraform Providers
        run: |
          terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64

      - name: Create secrets.tfvars
        run: |
          echo "project_id=\"$TF_VAR_PROJECT_ID\"" > secrets.tfvars
          echo "cloud_region=\"$TF_VAR_CLOUD_REGION\"" >> secrets.tfvars
          echo "zone=\"$TF_VAR_ZONE\"" >> secrets.tfvars
          echo "service_name=\"$TF_VAR_SERVICE_NAME\"" >> secrets.tfvars
          echo "image_url=\"$TF_VAR_IMAGE_URL\"" >> secrets.tfvars
          echo "tz=\"$TF_VAR_TZ\"" >> secrets.tfvars
          echo "log_level=\"$TF_VAR_LOG_LEVEL\"" >> secrets.tfvars
          echo "ai_prompt=\"$TF_VAR_AI_PROMPT\"" >> secrets.tfvars
          echo "t1_search_properties_url=\"$TF_VAR_T1_SEARCH_PROPERTIES_URL\"" >> secrets.tfvars
          echo "t1_imgs_pattern_prefix_url=\"$TF_VAR_T1_IMGS_PATTERN_PREFIX_URL\"" >> secrets.tfvars
          echo "t1_load_timeout_in_seconds=\"$TF_VAR_T1_LOAD_TIMEOUT_IN_SECONDS\"" >> secrets.tfvars
          echo "t1_xpath_timeout_in_seconds=\"$TF_VAR_T1_XPATH_TIMEOUT_IN_SECONDS\"" >> secrets.tfvars
          echo "server_host=\"$TF_VAR_SERVER_HOST\"" >> secrets.tfvars
          echo "server_port=\"$TF_VAR_SERVER_PORT\"" >> secrets.tfvars
          echo "cloudamqp_url=\"$TF_VAR_CLOUDAMQP_URL\"" >> secrets.tfvars
          echo "openai_api_key=\"$TF_VAR_OPENAI_API_KEY\"" >> secrets.tfvars
          echo "perplexity_api_key=\"$TF_VAR_PERPLEXITY_API_KEY\"" >> secrets.tfvars
          echo "mongodb_url=\"$TF_VAR_MONGODB_URL\"" >> secrets.tfvars
          echo "mongodb_database=\"$TF_VAR_MONGODB_DATABASE\"" >> secrets.tfvars
          echo "mongodb_user=\"$TF_VAR_MONGODB_USER\"" >> secrets.tfvars
          echo "mongodb_password=\"$TF_VAR_MONGODB_PASSWORD\"" >> secrets.tfvars
          echo "property_collection_name=\"$TF_VAR_PROPERTY_COLLECTION_NAME\"" >> secrets.tfvars

      - name: Terraform Destroy
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform destroy -auto-approve -var-file=secrets.tfvars

      - name: Terraform Refresh
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform refresh -var-file=secrets.tfvars

      - name: Terraform State List
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform state list

      - name: Terraform Plan
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform plan -out=tfplan.out -var-file=secrets.tfvars

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve tfplan.out
