name: Continuous Deployment to GCP [Infra-Linux]

on:
  push:
    branches:
      - "**"
    paths:
      - "gcp-infrastructure/**"
      - ".github/workflows/continuous-deployment-gcp-linux.yml"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "continuous-deployment-gcp"
  cancel-in-progress: false

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Get the microservice version from README.md
        id: version
        run: |
          echo "PRP_PRD=$(cat README.md | grep -o -P '(?<=<!-- etl-prd-start -->).*(?=<!-- etl-prd-end -->)')" >> $GITHUB_ENV

      - name: Build Image URL
        id: build_image_url
        run: |
          echo "IMAGE_URL=${{ vars.DOCKER_REGISTRY }}/jtsato/${{ vars.ARTIFACT_NAME }}:${{ env.PRP_PRD }}" >> $GITHUB_ENV

      - name: Set Environment Variables from GitHub Secrets
        env:
          IMAGE_URL: ${{ env.IMAGE_URL }}
          PRP_PRD: ${{ env.PRP_PRD }}
        run: |
          echo "TF_LOG=debug" >> $GITHUB_ENV
          echo "TF_VAR_PROJECT_ID=${{ vars.PROJECT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_PROJECT_OWNER=${{ secrets.PROJECT_OWNER }}" >> $GITHUB_ENV
          echo "TF_VAR_CLOUD_REGION=${{ vars.CLOUD_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_BUCKET_NAME=${{ vars.BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Terraform Version
        run: terraform -version

      - name: Terraform Init
        working-directory: gcp-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Terraform validate
        working-directory: gcp-infrastructure
        run: |
          terraform validate

      - name: Verify Terraform Providers
        working-directory: gcp-infrastructure
        run: |
          terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64

      - name: Create secrets.tfvars
        working-directory: gcp-infrastructure
        run: |
          echo "project_id=\"$TF_VAR_PROJECT_ID\"" > secrets.tfvars
          echo "project_owner=\"$TF_VAR_PROJECT_OWNER\"" >> secrets.tfvars
          echo "cloud_region=\"$TF_VAR_CLOUD_REGION\"" >> secrets.tfvars
          echo "bucket_name=\"$TF_VAR_BUCKET_NAME\"" >> secrets.tfvars

      - name: Terraform Destroy
        working-directory: gcp-infrastructure
        continue-on-error: true
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform destroy -auto-approve -var-file=secrets.tfvars

      - name: Terraform Refresh
        working-directory: gcp-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform refresh -var-file=secrets.tfvars

      - name: Terraform State List
        working-directory: gcp-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform state list

      - name: Terraform Plan
        working-directory: gcp-infrastructure
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform plan -out=tfplan.out -var-file=secrets.tfvars

      - name: Terraform Apply
        working-directory: gcp-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve tfplan.out
