name: Continuous Deployment to VPS [Linux]

on:
  push:
    branches:
      - "**"
    paths: 
      - "vps-infrastructure/**"
      - ".github/workflows/continuous-deployment-vps-linux.yml"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "continuous-deployment-vps"
  cancel-in-progress: false        

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Get the microservice version from README.md
        id: version
        run: |
          echo "PRP_PRD=$(cat README.md | grep -o -P '(?<=<!-- etl-prd-start -->).*(?=<!-- etl-prd-end -->)')" >> $GITHUB_ENV

      - name: Build Image URL
        id: build_image_url
        run: |
          echo "IMAGE_URL=${{ vars.DOCKER_REGISTRY }}/jtsato/${{ vars.ARTIFACT_NAME }}:${{ env.PRP_PRD }}" >> $GITHUB_ENV

      - name: Set Environment Variables from GitHub Secrets
        env:
          IMAGE_URL: ${{ env.IMAGE_URL }}
          PRP_PRD: ${{ env.PRP_PRD }}
        run: |
          echo "TF_LOG=debug" >> $GITHUB_ENV
          echo "TF_VAR_SSH_USER=${{ secrets.SSH_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_HOST=${{ secrets.SSH_HOST }}" >> $GITHUB_ENV
          echo "TF_VAR_SSH_PORT=${{ secrets.SSH_PORT }}" >> $GITHUB_ENV

      - name: Terraform Version
        run: terraform -version

      - name: Terraform Init
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Terraform validate
        working-directory: vps-infrastructure
        run: |
          terraform validate

      - name: Create secrets.tfvars
        working-directory: vps-infrastructure
        run: |
          echo "ssh_user=\"$TF_VAR_SSH_USER\"" >> secrets.tfvars
          echo "ssh_password=\"$TF_VAR_SSH_PASSWORD\"" >> secrets.tfvars
          echo "ssh_host=\"$TF_VAR_SSH_HOST\"" >> secrets.tfvars
          echo "ssh_port=\"$TF_VAR_SSH_PORT\"" >> secrets.tfvars

      - name: Terraform Destroy
        working-directory: vps-infrastructure
        continue-on-error: true
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform destroy -auto-approve -var-file=secrets.tfvars

      - name: Terraform Refresh
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform refresh -var-file=secrets.tfvars

      - name: Terraform State List
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform state list

      - name: Terraform Plan
        working-directory: vps-infrastructure
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform plan -out=tfplan.out -var-file=secrets.tfvars

      - name: Terraform Apply
        working-directory: vps-infrastructure
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve tfplan.out
